title: paw
description: "It's me, hi! I'm David"
url: https://davidfegyver.hu
favicon: logo.png

webneko: lucy
goat_counter: davidfegyver

last_fm_user: davidfegyver
last_fm_api_key: 6c60864eaab9bc3875fa75cf5b24a8e6

webmaster_verifications:
  google: QlpgsFeXJ92YJisKlt_pTwRiaBrcocunPdk80kB8DC8

socials:
  - name: "instagram"
    url: https://instagram.com/davidfegyver
  - name: "github"
    url: "https://github.com/davidfegyver"
  - name: "discord"
    text: "@pawfessional"
  - text: "root@davidfegyver.hu"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

include:
  - _pages
  - _posts

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore

collections:
  posts:
    output: true 
    permalink: /blog/:year/:month/:title/

birthdate: 2006-08-02

friends: 
  - name: "dcs0"
    url: "https://dcs0.hu/"
  - name: "levy"
    url: "https://leventefazekas.hu/"